// Seleciona o a pesquisa e atribui um evento de submit...
document.querySelector('.weather__search').addEventListener('submit', async (event) => {
    event.preventDefault();

    let input = document.querySelector('#searchInput').value; // Pega o valor do input...

    if (input !== '') { // Verifica se o input é diferente de vazio...
        showWarning('Carregando...'); // Chamando função de warning...

        // Dados da api...
        let apiKey = 'ea16a4bf88f8fbed3b160dcd7c5c549d'; // chave da minha conta...
        let apiMetric = 'metric'; // Métrica...
        let apiLang = 'pt_br'; // Linguagem...
        let apiUrl = `https://api.openweathermap.org/data/2.5/weather?q=${encodeURI(input)}&appid=${apiKey}&units=${apiMetric}&lang=${apiLang}`; // Url da api...

        let results = await fetch(apiUrl); // Faz a requisição e espera o resultado...
        let resultJson = await results.json(); // Pega o resultado e espera transformar em json...

        if (resultJson.cod === 200) { // Verifica se o retorno da api é igual a 200 (significa que encontrou a requisição)...
            showInfo({ // Montando o objeto de retorno...
                name: resultJson.name, // Pegando o nome...
                country: resultJson.sys.country, // Pegando o país...
                temp: resultJson.main.temp, // Pegando a temperatura...
                tempIcon: resultJson.weather[0].icon, // Pegando o ícone da temperatura...
                windSpeed: resultJson.wind.speed, // Pegando a velocidade do vento...
                windAngle: resultJson.wind.deg // Pegando a ângulo do vento...
            });

        } else { // Caso não encontre a requisição...
            clearInfo(); // Limpa as informações...
            showWarning('Não encontramos essa localização!'); // Informa que não encontrou...
        }

    } else { // Se o input tiver valor vazio...
        clearInfo(); // Limpa as informações...
    }
});

function showInfo(json) { // Lida com a exibição das informações...
    showWarning(''); // Para remover o carregando...

    // Selecionando elementos...
    let weatherCity = document.querySelector('.weather__city');
    let weatherTemperature = document.querySelector('.weather__item.temperature__');
    let weatherWind = document.querySelector('.weather__item.wind__');
    let weatherPoint = document.querySelector('.weather__item__point');
    let weatherResult = document.querySelector('.weather__result');

    document.querySelector('.weather__item img').setAttribute('src', `http://openweathermap.org/img/wn/${json.tempIcon}@2x.png`);

    // Aplica ações nos elementos...
    weatherCity.innerHTML = `${json.name}, ${json.country}`;
    weatherTemperature.innerHTML = `${json.temp} <sup>°C</sup>`;
    weatherWind.innerHTML = `${json.windSpeed} <span>km/h</span>`;

    weatherPoint.style.transform = `rotate(${json.windAngle - 90}deg)`;
    weatherResult.style.display = 'block';
}

function clearInfo() { // Lidando com a limpeza...
    showWarning(''); // Para remover o carregando...

    let weatherResult = document.querySelector('.weather__result');
    weatherResult.style.display = 'none';
}

function showWarning(message) { // Lidando com exibição do warning...
    let weatherWarning = document.querySelector('.weather__warning');
    weatherWarning.innerHTML = message;
}